[package]
name = "zenyx"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.94"
chrono = "0.4.39"
colored = "2.2.0"

lazy_static.workspace = true
log = "0.4.22"
once_cell = "1.20.2"
parking_lot.workspace = true
regex = "1.11.1"
rustyline = { version = "15.0.0", features = ["derive", "rustyline-derive"] }
tokio = { version = "1.42.0", features = ["macros", "parking_lot", "rt", "rt-multi-thread"] }
