// This file is automatically generated by build.rs
// Do not edit this file manually!

use horizon_plugin_api::{Pluginstate, LoadedPlugin, Plugin};
use std::collections::HashMap;

pub use eclypse;
pub use eclypse::*;
pub use eclypse::Plugin as eclypse_plugin;


// Invoke the macro with all discovered plugins
pub fn load_plugins() -> HashMap<String, (Pluginstate, Plugin)> {
    let plugins = crate::load_plugins!(
        eclypse
    );
    plugins
}
