name: Build Zenyx ⚡
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy, rustfmt
    
    - name: Check formatting
      run: |
        if ! cargo fmt -- --check; then
          echo "Formatting check failed. Run 'cargo fmt' to fix."
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            exit 1
          fi
        fi
    
    - name: Run Clippy
      run: |
        if ! cargo clippy -- -D warnings; then
          echo "Clippy found warnings. Address these before merging."
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            exit 1
          fi
        fi

  check-version:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check.outputs.should_release }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
     
      - name: Check if Cargo.toml version changed
        id: check
        run: |
          CURRENT_VERSION=$(grep -m1 version Cargo.toml | cut -d '"' -f2)
          git checkout HEAD^1
          PREVIOUS_VERSION=$(grep -m1 version Cargo.toml | cut -d '"' -f2)
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "should_release=true" >> $GITHUB_OUTPUT
            echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: [code-quality, check-version]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x86_64, aarch64]
        include:
          - arch: x86_64
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            arch: x86_64
            target: x86_64-apple-darwin
          - arch: aarch64
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            arch: aarch64
            target: aarch64-apple-darwin
          - os: windows-latest
            arch: x86_64
            target: x86_64-pc-windows-msvc
        exclude:
          - os: windows-latest
            arch: aarch64
    runs-on: ${{ matrix.os }}
    steps:
    - name: 📥 Clone repository
      uses: actions/checkout@v3
   
    - name: 🛠️ Install cross-compilation dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu qemu-user
    - name: 🛠️ Install cross-compilation dependencies (macOS🍎)
      if: runner.os == 'macOS'
      run: |
        brew install FiloSottile/musl-cross/musl-cross
       
    - name: 🔧 Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: ${{ matrix.target }}
        profile: minimal
   
    - name: 🏗️ Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target ${{ matrix.target }}
      env:
        CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
     
    - name: 🧪 Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --target ${{ matrix.target }}
      env:
        CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
        QEMU_LD_PREFIX: /usr/aarch64-linux-gnu
    - name: 📦 Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Zenyx-${{ runner.os }}-${{ matrix.arch }}-bin
        path: target/${{ matrix.target }}/release/zenyx*